- name: Installing tools for python dev
  become: true
  ansible.builtin.package:
    name:
      - python
      # NOTE: different names on different platforms
      # - pip
      # - pipx

      - uv
    state: latest

- name: Installing ty typechecker
  ansible.builtin.command:
    cmd: "uv tool install ty@latest"
  changed_when: false

- name: Installing ruff lineter
  ansible.builtin.command:
    cmd: "uv tool install ruff@latest"
  changed_when: false

