- name: Installing ansible packages
  become: true
  ansible.builtin.package:
    name:
      - ansible
      # NOTE: different names on different platforms
      # - python3-github3py
      # - python3-rpm
    state: latest

